return {
	"stevearc/aerial.nvim",
	opts = {
		close_automatic_events = {
			"unfocus",
			"switch_buffer",
		},
		guides = {
			nested_top = " │ ",
			mid_item = " ├─",
			last_item = " └─",
			whitespace = "   ",
		},
		layout = {
			placement = "window",
			close_on_select = false,
			max_width = 30,
			min_width = 30,
		},
		ignore = {
			buftypes = {},
		},
		icons = {
			Array = " 󰅪 ",
			BlockMappingPair = " 󰅩 ",
			Boolean = "  ",
			BreakStatement = " 󰙧 ",
			Call = " 󰃷 ",
			CaseStatement = " 󰨚 ",
			Class = "  ",
			Color = "  ",
			Constant = "  ",
			Constructor = " 󰆧 ",
			ContinueStatement = "  ",
			Copilot = "  ",
			Declaration = " 󰙠 ",
			Delete = " 󰩺 ",
			DoStatement = " 󰑖 ",
			Element = " 󰅩 ",
			Enum = "  ",
			EnumMember = "  ",
			Event = "  ",
			Field = "  ",
			File = "  ",
			Folder = "  ",
			ForStatement = "󰑖 ",
			Function = " 󰆧 ",
			GotoStatement = " 󰁔 ",
			Identifier = " 󰀫 ",
			IfStatement = " 󰇉 ",
			Interface = "  ",
			Keyword = "  ",
			List = " 󰅪 ",
			Log = " 󰦪 ",
			Lsp = "  ",
			Macro = " 󰁌 ",
			MarkdownH1 = " 󰉫 ",
			MarkdownH2 = " 󰉬 ",
			MarkdownH3 = " 󰉭 ",
			MarkdownH4 = " 󰉮 ",
			MarkdownH5 = " 󰉯 ",
			MarkdownH6 = " 󰉰 ",
			Method = " 󰆧 ",
			Module = " 󰅩 ",
			Namespace = " 󰅩 ",
			Null = " 󰢤 ",
			Number = " 󰎠 ",
			Object = " 󰅩 ",
			Operator = "  ",
			Package = " 󰆧 ",
			Pair = " 󰅪 ",
			Property = "  ",
			Reference = "  ",
			Regex = "  ",
			Repeat = " 󰑖 ",
			Return = " 󰌑 ",
			RuleSet = " 󰅩 ",
			Scope = " 󰅩 ",
			Section = " 󰅩 ",
			Snippet = "  ",
			Specifier = " 󰦪 ",
			Statement = " 󰅩 ",
			String = "  ",
			Struct = "  ",
			SwitchStatement = " 󰨙 ",
			Table = " 󰅩 ",
			Terminal = "  ",
			Text = " 󰀬 ",
			Type = "  ",
			TypeParameter = "  ",
			Unit = "  ",
			Value = "  ",
			Variable = "  ",
			WhileStatement = " 󰑖 ",
		},
		show_guides = true,
		open_automatic = function()
			local aerial = require("aerial")
			return vim.api.nvim_win_get_width(0) > 80 and not aerial.was_closed()
		end,
	},
	config = function(_, opts)
		require("aerial").setup(opts)
		vim.keymap.set("n", "<leader>at", "<cmd>AerialToggle<cr>", { silent = true })
	end,
}
